services:
  web:
    build:
      context: web
      args:
        NEXT_PUBLIC_API: https://localhost/api
    restart: always
    networks:
      - nginx

  api:
    build: api
    restart: always
    networks:
      - nginx

  nginx:
    build:
      context: nginx
      args:
        HOST: localhost
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - nginx
    volumes:
      - ./felys.dev.pem:/etc/ssl/certs/felys.dev.pem:ro
      - ./felys.dev.key:/etc/ssl/private/felys.dev.key:ro
      - /dev/null:/etc/nginx/conf.d/default.conf

networks:
  nginx:
    name: nginx
