services:
  web:
    build:
      context: web
      args:
        NEXT_PUBLIC_API: https://exec.felys.dev/api
    image: felysneko/felys-web:latest

  api:
    build: api
    image: felysneko/felys-api:latest
